name: iOS Build

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up code signing
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.IOS_CERTIFICATES_P12 }}
          p12-password: ${{ secrets.IOS_CERTIFICATES_P12_PASSWORD }}
          
      - name: Build and export IPA
        run: |
          xcodebuild archive -project mdcX_ZH/mdcX.xcodeproj -scheme mdcX -archivePath build/mdcX.xcarchive
          xcodebuild -exportArchive -archivePath build/mdcX.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist
          
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: mdcX-app
          path: build/mdcX_ZH.ipa
