name: Basic Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Basic Build Attempt
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List directory structure
        run: |
          ls -la
          find . -name "*.xcodeproj" -type d
      
      - name: Attempt direct build
        run: |
          cd mdcX_ZH
          xcodebuild build -project mdcX.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO IPHONEOS_DEPLOYMENT_TARGET=16.0 -configuration Debug
