name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List directory structure
        run: |
          ls -la
          find . -name "*.xcodeproj" -type d
      
      - name: List available targets
        run: |
          xcodebuild -project mdcX_ZH/mdcX.xcodeproj -list
      
      - name: Build with absolute path
        run: |
          cd mdcX_ZH && xcodebuild -project mdcX.xcodeproj -target mdcX CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO IPHONEOS_DEPLOYMENT_TARGET=16.0
