name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Install the Apple certificate and provisioning profile
        run: |
          # 为CI环境配置临时证书或使用自动签名
          xcodebuild -project mdcX_ZH/mdcX.xcodeproj -scheme mdcX -configuration Debug -allowProvisioningUpdates build
      - name: Build
        run: |
          xcodebuild build -project mdcX_ZH/mdcX.xcodeproj -scheme mdcX CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
